import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { InvoiceData } from "../types";

export const generateInvoicePDF = (data: InvoiceData): string => {
  const doc = new jsPDF();

  // --- Header Section ---
  doc.setFillColor(15, 118, 110); // Teal 700 (matching bg-teal-700)
  doc.rect(0, 0, 210, 40, "F");

  // Logo / Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("BillKaro", 14, 26);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Fast & Smart Billing Solutions", 14, 33);

  doc.setFontSize(12);
  doc.text("INVOICE", 195, 26, { align: "right" });

  // --- Info Section ---
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);

  // Customer Details (Left)
  const startY = 55;
  doc.setFont("helvetica", "bold");
  doc.text("BILLED TO:", 14, startY);
  
  doc.setFont("helvetica", "normal");
  doc.text(data.customer.name || "Walk-in Customer", 14, startY + 6);
  
  let currentY = startY + 11;
  if (data.customer.mobile) {
    doc.text(`+91 ${data.customer.mobile}`, 14, currentY);
    currentY += 5;
  }

  if (data.customer.email) {
      doc.text(data.customer.email, 14, currentY);
      currentY += 5;
  }
  
  if (data.customer.address) {
      const addressLines = doc.splitTextToSize(data.customer.address, 80);
      doc.text(addressLines, 14, currentY + 1);
  }

  // Invoice Details (Right)
  doc.text(`Invoice No:`, 140, startY);
  doc.setFont("helvetica", "bold");
  doc.text(data.invoiceNumber, 175, startY);
  
  doc.setFont("helvetica", "normal");
  doc.text(`Date:`, 140, startY + 6);
  doc.setFont("helvetica", "bold");
  doc.text(data.date, 175, startY + 6);

  // --- Table Section ---
  // Prepare body data
  let subtotal = 0;
  let totalGST = 0;

  const tableRows = data.items.map((item, index) => {
    const taxable = item.quantity * item.rate;
    const gstAmt = (taxable * item.gstRate) / 100;
    const total = taxable + gstAmt;

    subtotal += taxable;
    totalGST += gstAmt;

    return [
      index + 1,
      item.name,
      item.quantity,
      `Rs. ${item.rate.toFixed(2)}`,
      `${item.gstRate}%`,
      `Rs. ${gstAmt.toFixed(2)}`,
      `Rs. ${total.toFixed(2)}`,
    ];
  });

  const grandTotal = subtotal + totalGST;

  autoTable(doc, {
    startY: 85,
    head: [["#", "Item Name", "Qty", "Rate", "GST %", "Tax", "Total"]],
    body: tableRows,
    theme: "grid",
    headStyles: {
      fillColor: [15, 118, 110],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    columnStyles: {
      0: { halign: "center" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "center" },
      5: { halign: "right" },
      6: { halign: "right", fontStyle: "bold" },
    },
  });

  // --- Totals Section ---
  // @ts-ignore
  const finalY = doc.lastAutoTable.finalY + 10;
  
  // Right align calculation helper
  const rightColX = 195;
  const labelColX = 140;
  
  doc.setFontSize(10);
  
  // Subtotal
  doc.setFont("helvetica", "normal");
  doc.text("Subtotal (Taxable):", labelColX, finalY);
  doc.text(`Rs. ${subtotal.toFixed(2)}`, rightColX, finalY, { align: "right" });

  // CGST
  doc.text("CGST:", labelColX, finalY + 6);
  doc.text(`Rs. ${(totalGST / 2).toFixed(2)}`, rightColX, finalY + 6, { align: "right" });

  // SGST
  doc.text("SGST:", labelColX, finalY + 12);
  doc.text(`Rs. ${(totalGST / 2).toFixed(2)}`, rightColX, finalY + 12, { align: "right" });

  // Divider
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(labelColX, finalY + 16, rightColX, finalY + 16);

  // Grand Total
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 118, 110); // Teal
  doc.text("Grand Total:", labelColX, finalY + 24);
  doc.text(`Rs. ${Math.round(grandTotal).toFixed(2)}`, rightColX, finalY + 24, { align: "right" });

  // Amount in words (simple placeholder or actual logic could go here)
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "italic");
  doc.text(`Total Items: ${data.items.length}`, 14, finalY + 24);

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.height;
  
  // Authorized Signatory
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Authorized Signatory", 195, pageHeight - 30, { align: "right" });
  doc.setLineWidth(0.2);
  doc.line(145, pageHeight - 35, 195, pageHeight - 35); // Signature line

  // Footer Branding
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by BillKaro", 105, pageHeight - 10, { align: "center" });

  // Save the PDF
  doc.save(`BillKaro_Invoice_${data.invoiceNumber}.pdf`);

  // Return base64 string (remove data URL prefix for raw base64)
  const dataUri = doc.output('datauristring');
  return dataUri.split(',')[1];
};